### ISSUE TITLE
clock_gettime needs librt

### ISSUE THREAD

**Issue by guangmuzhu** [octo/liboping#14]
librt is only checked for nanosleep while it's also needed by clock_gettime, which results in a link error.

**Comment by octo** [comment]
A check for `clock_gettime()` was introduced in 6e83f8b261a05afe7bf9fdb9005c4c1aa3e97fed. In the mean time, the use of `clock_gettime()` was replaced with `gettimeofday()` (#19) because the former is not available on Mac OS X.
