### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by unit309** [octo/liboping#17]
Is it possible to use transparent background color instead of black?
On terminal with black background, there will be no difference.
On terminal with transparent background, it will be nice and convinient,

My use case, right now: terminal window on first pane, splitted, with server log (transparent) and noping to some clients (sadly, black BG), and server load graphs in underlying browser window (still visible through VPN log).

BTW:thnx4yowrk!

**Comment by middleO** [comment]
I also would like to see this implemented. I compiled from source with [this](https://linux.die.net/man/3/use_default_colors) and end result is what @unit309 suggested. It also has added benefit of noping obeying terminal emulators color palette.

Anyway, I would like to see this implemented in base project.

Thanks @octo for great project. Liboping and noping has been of great value for me.

**Comment by octo** [comment]
Thanks for filing this feature request, @unit309!

@middleO I don't currently have much time available to work on such a feature, but if you file a pull request with your changes I'm happy to review it :)
