### ISSUE TITLE
clock_gettime (CLOCK_REALTIME, &ts) doesn't work on OS X < 10.12

### ISSUE THREAD

**Issue by mojca** [octo/liboping#19]
Commit dbfc310d1305d1c6a6e3d6eaa9091ab7d4145c26 broke the build on all OS X versions other than 10.12 because
```c
clock_gettime (CLOCK_REALTIME, &ts)
```
is not supported on older OSes.

See: http://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x

**Comment by octo** [comment]
Hi @mojca,

thank you very much for reporting this issue. I've replaced `clock_gettime()` with `gettimeofday()` in the one location is was used, so this should compile cleanly on Mac OS X again :)

Best regards,
—octo
