### ISSUE TITLE
noping exits every once a while printing `ping_sendto: No buffer space available`

### ISSUE THREAD

**Issue by l29ah** [octo/liboping#28]
git master

**Comment by octo** [comment]
Hi @l29ah, thank you very much for reporting this!

Sounds like `ping_sendto()` is returning the error `ENOBUFS`:

```c
        status = ping_sendto (obj, ph, buf, buflen, fd);
        if (status < 0)
        {
                perror ("ping_sendto");
                return (-1);
        }
```

liboping itself does not use this constant, so it must be returned by a system call. `gettimeofday()` seems unlikely, leaving only `sendto()`. The spec has this to say:

> [ENOBUFS]
> Insufficient resources were available in the system to perform the operation.

The Linux manpages say this:

> ENOBUFS
> The  output  queue  for  a network interface was full.  This generally indicates that the interface has stopped sending, but may be caused by transient congestion.  (Normally, this does not occur in Linux.  Packets are just silently dropped when a device queue overflows.)

What kind of system are you using? Does the machine (occasionally) saturate its upstream?

Best regards,
—octo

**Comment by l29ah** [comment]
On Tue, Sep 05, 2017 at 06:48:53AM +0000, Florian Forster wrote:
> What kind of system are you using? Does the machine (occasionally) saturate its upstream?

Gentoo Linux. It might be, it's quite narrow here.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments
