### ISSUE TITLE
commit c768cc2270d49247 leads to endless looping

### ISSUE THREAD

**Issue by cron2** [octo/liboping#54]
Hi,

the commit c768cc2270d49247 changes the way how ping_send() errors are handled, from "abort program" to "retry".  This might be a reasonable thing for ENOBUFS errors, but it leads to fast looping for hosts on the local LAN where ARP fails.   This might be a BSD thing, but if you have a locally connected host, and ARP fails, eventually you get back a "Host is down" error on sending packets - which leads to a very fast scrolling of

ping_sendto: Host is down
ping_send failed: Host is down
ping_sendto: Host is down
ping_send failed: Host is down
ping_sendto: Host is down
ping_send failed: Host is down
ping_sendto: Host is down
ping_send failed: Host is down
ping_sendto: Host is down
ping_send failed: Host is down
ping_sendto: Host is down
ping_send failed: Host is down
ping_sendto: Host is down
ping_send failed: Host is down
ping_sendto: Host is down

now...

I think a better way to handle ping_send errors would be to just report them as error in the normal timing (1 second, whatever) and plot them as "___E___" in the graphical display.

**Comment by cron2** [comment]
Ah.  Debugged some more.  BSDs return "EHOSTDOWN" (errno=64) for this case, which is not currently handled in liboping.c.  Fix is trivial

#if defined(EHOSTDOWN)
                if (errno == EHOSTDOWN)
                        return (0);
#endif

PR will come right away.

**Comment by octo** [comment]
Thanks for reporting and investigating @cron2! It sounds like #55 fixed this issue. Can it be closed?

Best regards,
—octo

**Comment by cron2** [comment]
Hi @octo 

good morning and thanks for looking into this :-) - yes, the "it will crash or loop" behaviour is fixed with #55 .  

I still think it would be nice to see actual sendto() errors in the oping/noping out differently from "just a timeout", but that's a bit more complicated than I thought (save the "there was an error of this particular class at sending" somewhere, and evaluate that on "receiving") - but that's a different topic, and will show up with a new PR for review and discussion :-)

So, this can be closed.

cron2
